In [2]:
import numpy as np
import xarray as xr

In [3]:
da1 = xr.DataArray(np.random.randn(2, 3), [('x', ['a', 'b']), ('y', [10, 20, 30])])
da1

<xarray.DataArray (x: 2, y: 3)>
array([[-0.677337, -0.777142,  0.916852],
       [-0.31313 ,  0.341775, -0.416006]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30

In [4]:
da2 = xr.DataArray(np.random.randn(2, 3), [('x', ['c', 'd']), ('y', [40, 50, 60])])
da2

<xarray.DataArray (x: 2, y: 3)>
array([[-0.665198,  0.634057, -0.003932],
       [ 0.383107,  0.828298,  0.971749]])
Coordinates:
  * x        (x) <U1 'c' 'd'
  * y        (y) int64 40 50 60

In [5]:
da3 = xr.DataArray(np.random.randn(2, 2), [('x', ['b', 'c']), ('y', [30, 40])])
da3

<xarray.DataArray (x: 2, y: 2)>
array([[ 0.648664, -1.197077],
       [-1.234978, -0.125411]])
Coordinates:
  * x        (x) <U1 'b' 'c'
  * y        (y) int64 30 40

In [6]:
xr.align(da1, da2, join="outer")

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


(<xarray.DataArray (x: 4, y: 6)>
 array([[-0.677337, -0.777142,  0.916852,       nan,       nan,       nan],
        [-0.31313 ,  0.341775, -0.416006,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60, <xarray.DataArray (x: 4, y: 6)>
 array([[      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan, -0.665198,  0.634057, -0.003932],
        [      nan,       nan,       nan,  0.383107,  0.828298,  0.971749]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60)

In [7]:
xr.align(da1, da2, da3, join="outer")

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


(<xarray.DataArray (x: 4, y: 6)>
 array([[-0.677337, -0.777142,  0.916852,       nan,       nan,       nan],
        [-0.31313 ,  0.341775, -0.416006,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60, <xarray.DataArray (x: 4, y: 6)>
 array([[      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan, -0.665198,  0.634057, -0.003932],
        [      nan,       nan,       nan,  0.383107,  0.828298,  0.971749]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60, <xarray.DataArray (x: 4, y: 6)>
 array([[      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,  

In [9]:
xr.concat(xr.align(da1, da2, da3, join="outer"), dim="y")

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


<xarray.DataArray (x: 4, y: 18)>
array([[-0.677337, -0.777142,  0.916852,       nan,       nan,       nan,
              nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan,       nan,       nan,       nan],
       [-0.31313 ,  0.341775, -0.416006,       nan,       nan,       nan,
              nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,  0.648664, -1.197077,       nan,       nan],
       [      nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan, -0.665198,  0.634057, -0.003932,
              nan,       nan, -1.234978, -0.125411,       nan,       nan],
       [      nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan,  0.383107,  0.828298,  0.971749,
              nan,       nan,       nan,       nan,       nan,       nan]])
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int6

In [10]:
xr.merge([da1, da2, da3])

ValueError: unable to convert unnamed DataArray to a Dataset without providing an explicit name

In [13]:
xr.merge(xr.align(da1, da2, da3, join="outer"))

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


ValueError: unable to convert unnamed DataArray to a Dataset without providing an explicit name

In [11]:
da1.combine_first(da2)

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


<xarray.DataArray (x: 4, y: 6)>
array([[-0.677337, -0.777142,  0.916852,       nan,       nan,       nan],
       [-0.31313 ,  0.341775, -0.416006,       nan,       nan,       nan],
       [      nan,       nan,       nan, -0.665198,  0.634057, -0.003932],
       [      nan,       nan,       nan,  0.383107,  0.828298,  0.971749]])
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int64 10 20 30 40 50 60

In [12]:
da1.combine_first(da3)

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


<xarray.DataArray (x: 3, y: 4)>
array([[-0.677337, -0.777142,  0.916852,       nan],
       [-0.31313 ,  0.341775, -0.416006, -1.197077],
       [      nan,       nan, -1.234978, -0.125411]])
Coordinates:
  * x        (x) object 'a' 'b' 'c'
  * y        (y) int64 10 20 30 40

In [14]:
da1.name = "da1"
da2.name = "da2"
da3.name = "da3"

In [15]:
xr.merge([da1, da2, da3])

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


<xarray.Dataset>
Dimensions:  (x: 4, y: 6)
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int64 10 20 30 40 50 60
Data variables:
    da1      (x, y) float64 -0.6773 -0.7771 0.9169 nan nan nan -0.3131 ...
    da2      (x, y) float64 nan nan nan nan nan nan nan nan nan nan nan nan ...
    da3      (x, y) float64 nan nan nan nan nan nan nan nan 0.6487 -1.197 ...