In [1]:
import os
import numpy as np
import pandas as pd
import xarray as xr
import mkgu
import peewee

In [2]:
hvm = mkgu.get_assembly("HvM")
hvm

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 270060, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ...,
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ...,
        [ 2.449372],
        [ 0.401197]],

       ...,

       [[ 1.121319],
        [ 1.719423],
        ...,
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ...,
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal           (neuroid) object 'Chabo' 'Ch

In [3]:
hvm_stripped = hvm.copy()
hvm_stripped

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 270060, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ...,
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ...,
        [ 2.449372],
        [ 0.401197]],

       ...,

       [[ 1.121319],
        [ 1.719423],
        ...,
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ...,
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal           (neuroid) object 'Chabo' 'Ch

In [4]:
to_remove = ['ryz_semantic', 'variation', 'image_file_name', 'rxy_semantic', 'size', 
             'category', 'object', 'tz', 'ty', 'rxz_semantic', 'rxy', 'background_id', 's', 'rxz', 'ryz']

In [5]:
for level in to_remove:
    if level in hvm_stripped.indexes["presentation"].names:
        hvm_stripped.reset_index(level, inplace=True)
        hvm_stripped.reset_coords(level, inplace=True, drop=True)
hvm_stripped

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 270060, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ...,
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ...,
        [ 2.449372],
        [ 0.401197]],

       ...,

       [[ 1.121319],
        [ 1.719423],
        ...,
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ...,
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid         (neuroid) MultiIndex
  - neuroid_id      (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr             (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col             (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere      (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion       (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal          (neuroid) object 'Chabo' 'C

In [6]:
df_stimulus = hvm.indexes["presentation"].to_frame()
df_stimulus

background_id  \
ryz_semantic object     variation image_id                                 image_file_name                                    rxy_semantic size  category tz     ty     rxz_semantic rxy        background_id                            s        rxz        ryz         repetition stimulus                                             
-0.000000    car_astra  V0        8a72e2bfdb8c267b57232bf96f069374d5b21832 astra_rx+00.000_ry+00.000_rz+00.000_tx+00.000_t...  90.000000   256.0 Cars      0.000  0.000  0.000000    -0.000000  ecd40f3f6d7a4d6d88134d648884e0b9b364efc9 1.000000  0.000000  -0.000000   0          0         ecd40f3f6d7a4d6d88134d648884e0b9b364efc9   
             table3     V0        27f69468c9d6019ed0d22b9583c94c5b58198c1c _12_rx+00.000_ry+00.000_rz+00.000_tx+00.000_ty+... -0.000000    256.0 Tables    0.000  0.000  0.000000    -0.000000  006d66c207c6417574f62f0560c6b2b40a9ec5a1 1.000000  0.000000  -0.000000   0          1         006d66c207c6417574f62f0560c6b2b40a9ec5a1   
             face2      V0        6af1cbb28aacea6c582faa07e92d8325fa7a29d7 face0003_rx+00.000_ry+00.000_rz+00.000_tx+00.00... -0.000000    256.0 Faces     0.000  0.000  0.000000    -0.000000  3b3c1d65865028d0fad0b0bf8f305098db717e7f 1.000000  0.000000  -0.000000   0          2         3b3c1d65865028d0fad0b0bf8f305098db717e7f   
             walnut     V0        d0f7a45b377d4920c3466ec7a20dce9437a150d6 walnut_obj_rx-90.000_ry+00.000_rz+00.000_tx+00.... -0.000000    256.0 Fruits    0.000  0.000  0.000000    -0.000000  687ade2f9ee4d52af9705865395471a24ba38d5f 1.000000  0.000000  -0.000000   0          3         687ade2f9ee4d52af9705865395471a24ba38d5f   
                                  d4c3b4d4aefd29fd168a2c3c9a9962d99653a715 walnut_obj_rx-90.000_ry+00.000_rz+00.000_tx+00.... -0.000000    256.0 Fruits    0.000  0.000  0.000000    -0.000000  724e5703cc42aa2c3ff135e3508038a90e4ebcb3 1.000000  0.000000  -0.000000   0          4         724e5703cc42aa2c3ff135e3508038a90e4ebcb3   
             airplane7  V0        c6fb4f35719f0f205f5ad65f4fd2794212c5d139 sopwith_rx+00.000_ry+00.000_rz+00.000_tx+00.000...  90.000000   256.0 Planes    0.000  0.000  0.000000    -0.000000  d6399fdb5cfe58a1c1908762cfe82406e2510231 1.000000  0.000000  -0.000000   0          5         d6399fdb5cfe58a1c1908762cfe82406e2510231   
             apricot    V0        ae2b8aac003c867a772647197dcd3c050b75a06e Apricot_obj_rx-90.000_ry+00.000_rz+00.000_tx+00... -0.000000    256.0 Fruits    0.000  0.000  0.000000    -0.000000  7b44fb43755d315da8e94d73a1ab04e5db592a04 1.000000  0.000000  -0.000000   0          6         7b44fb43755d315da8e94d73a1ab04e5db592a04   
             strawberry V0        a7a31e65e2770c7a503988835c24aeab689abf47 Strawberry_obj_rx-90.000_ry+00.000_rz+00.000_tx... -0.000000    256.0 Fruits    0.000  0.000  0.000000    -0.000000  03f46b6acdb2fc42f934c5ef67792026de49d530 1.000000  0.000000  -0.000000   0          7         03f46b6acdb2fc42f934c5ef67792026de49d530   
             face1      V0        09d2924723bc4677df666072b6e25e988d5f0668 face0002_rx+00.000_ry+00.000_rz+00.000_tx+00.00... -0.000000    256.0 Faces     0.000  0.000  0.000000    -0.000000  0e3b948ff7c95fcdd6bd07dc0d74b8e2c6ea0e25 1.000000  0.000000  -0.000000   0          8         0e3b948ff7c95fcdd6bd07dc0d74b8e2c6ea0e25   
             airplane4  V0        1df484a50ff7fbd85112990b7f8fe616c49adb28 junkers88_rx+00.000_ry+00.000_rz+00.000_tx+00.0...  90.000000   256.0 Planes    0.000  0.000  0.000000    -0.000000  2164801f3646e5e82eaa4373f8d249ce17edf1ac 1.000000  0.000000  -0.000000   0          9         2164801f3646e5e82eaa4373f8d249ce17edf1ac   
             ship1      V0        e134c3d8fa8be11c8eb0b8d55e7f534286f44736 CGTG_L_rx+00.000_ry+00.000_rz+00.000_tx+00.000_...  90.000000   256.0 Boats     0.000  0.000  0.000000    -0.000000  a7822b52b3d9b276234e9ef3d78e9e1a2aa0eeb9 1.000000  0.000000  -0.000000   0          10        a7822b52b3d9b276234e9ef3d78e9e1a2aa0eeb9   
             ship3     

In [7]:
df_images = df_stimulus[df_stimulus["variation"]!="nan"].drop(columns=["stimulus", "repetition"]).drop_duplicates()
df_images

background_id  \
ryz_semantic object     variation image_id                                 image_file_name                                    rxy_semantic size  category tz     ty     rxz_semantic rxy        background_id                            s        rxz        ryz         repetition stimulus                                             
-0.000000    car_astra  V0        8a72e2bfdb8c267b57232bf96f069374d5b21832 astra_rx+00.000_ry+00.000_rz+00.000_tx+00.000_t...  90.000000   256.0 Cars      0.000  0.000  0.000000    -0.000000  ecd40f3f6d7a4d6d88134d648884e0b9b364efc9 1.000000  0.000000  -0.000000   0          0         ecd40f3f6d7a4d6d88134d648884e0b9b364efc9   
             table3     V0        27f69468c9d6019ed0d22b9583c94c5b58198c1c _12_rx+00.000_ry+00.000_rz+00.000_tx+00.000_ty+... -0.000000    256.0 Tables    0.000  0.000  0.000000    -0.000000  006d66c207c6417574f62f0560c6b2b40a9ec5a1 1.000000  0.000000  -0.000000   0          1         006d66c207c6417574f62f0560c6b2b40a9ec5a1   
             face2      V0        6af1cbb28aacea6c582faa07e92d8325fa7a29d7 face0003_rx+00.000_ry+00.000_rz+00.000_tx+00.00... -0.000000    256.0 Faces     0.000  0.000  0.000000    -0.000000  3b3c1d65865028d0fad0b0bf8f305098db717e7f 1.000000  0.000000  -0.000000   0          2         3b3c1d65865028d0fad0b0bf8f305098db717e7f   
             walnut     V0        d0f7a45b377d4920c3466ec7a20dce9437a150d6 walnut_obj_rx-90.000_ry+00.000_rz+00.000_tx+00.... -0.000000    256.0 Fruits    0.000  0.000  0.000000    -0.000000  687ade2f9ee4d52af9705865395471a24ba38d5f 1.000000  0.000000  -0.000000   0          3         687ade2f9ee4d52af9705865395471a24ba38d5f   
                                  d4c3b4d4aefd29fd168a2c3c9a9962d99653a715 walnut_obj_rx-90.000_ry+00.000_rz+00.000_tx+00.... -0.000000    256.0 Fruits    0.000  0.000  0.000000    -0.000000  724e5703cc42aa2c3ff135e3508038a90e4ebcb3 1.000000  0.000000  -0.000000   0          4         724e5703cc42aa2c3ff135e3508038a90e4ebcb3   
             airplane7  V0        c6fb4f35719f0f205f5ad65f4fd2794212c5d139 sopwith_rx+00.000_ry+00.000_rz+00.000_tx+00.000...  90.000000   256.0 Planes    0.000  0.000  0.000000    -0.000000  d6399fdb5cfe58a1c1908762cfe82406e2510231 1.000000  0.000000  -0.000000   0          5         d6399fdb5cfe58a1c1908762cfe82406e2510231   
             apricot    V0        ae2b8aac003c867a772647197dcd3c050b75a06e Apricot_obj_rx-90.000_ry+00.000_rz+00.000_tx+00... -0.000000    256.0 Fruits    0.000  0.000  0.000000    -0.000000  7b44fb43755d315da8e94d73a1ab04e5db592a04 1.000000  0.000000  -0.000000   0          6         7b44fb43755d315da8e94d73a1ab04e5db592a04   
             strawberry V0        a7a31e65e2770c7a503988835c24aeab689abf47 Strawberry_obj_rx-90.000_ry+00.000_rz+00.000_tx... -0.000000    256.0 Fruits    0.000  0.000  0.000000    -0.000000  03f46b6acdb2fc42f934c5ef67792026de49d530 1.000000  0.000000  -0.000000   0          7         03f46b6acdb2fc42f934c5ef67792026de49d530   
             face1      V0        09d2924723bc4677df666072b6e25e988d5f0668 face0002_rx+00.000_ry+00.000_rz+00.000_tx+00.00... -0.000000    256.0 Faces     0.000  0.000  0.000000    -0.000000  0e3b948ff7c95fcdd6bd07dc0d74b8e2c6ea0e25 1.000000  0.000000  -0.000000   0          8         0e3b948ff7c95fcdd6bd07dc0d74b8e2c6ea0e25   
             airplane4  V0        1df484a50ff7fbd85112990b7f8fe616c49adb28 junkers88_rx+00.000_ry+00.000_rz+00.000_tx+00.0...  90.000000   256.0 Planes    0.000  0.000  0.000000    -0.000000  2164801f3646e5e82eaa4373f8d249ce17edf1ac 1.000000  0.000000  -0.000000   0          9         2164801f3646e5e82eaa4373f8d249ce17edf1ac   
             ship1      V0        e134c3d8fa8be11c8eb0b8d55e7f534286f44736 CGTG_L_rx+00.000_ry+00.000_rz+00.000_tx+00.000_...  90.000000   256.0 Boats     0.000  0.000  0.000000    -0.000000  a7822b52b3d9b276234e9ef3d78e9e1a2aa0eeb9 1.000000  0.000000  -0.000000   0          10        a7822b52b3d9b276234e9ef3d78e9e1a2aa0eeb9   
             ship3     

In [133]:
df_images.shape

(5760, 16)

In [9]:
hvm_stripped.shape

(296, 270060, 1)

In [10]:
hvm_stripped_copy = hvm_stripped.copy()
hvm_stripped_copy

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 270060, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ...,
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ...,
        [ 2.449372],
        [ 0.401197]],

       ...,

       [[ 1.121319],
        [ 1.719423],
        ...,
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ...,
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid         (neuroid) MultiIndex
  - neuroid_id      (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr             (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col             (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere      (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion       (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal          (neuroid) object 'Chabo' 'C

In [136]:
# da_dummy_value["object"] = ("value", da_dummy_value.indexes["value"].to_frame().merge(df_dummy_meta, on="image_id", how="left")["object"])
hvm_stripped_copy["object"] = ("presentation", hvm_stripped_copy.indexes["presentation"].to_frame().merge(df_images, on="image_id", how="left")["object"])
hvm_stripped_copy

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 270060, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ...,
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ...,
        [ 2.449372],
        [ 0.401197]],

       ...,

       [[ 1.121319],
        [ 1.719423],
        ...,
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ...,
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid         (neuroid) MultiIndex
  - neuroid_id      (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr             (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col             (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere      (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion       (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal          (neuroid) object 'Chabo' 'C

In [137]:
hvm_stripped_copy.set_index(append=True, inplace=True, presentation=["object"])
hvm_stripped_copy

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 270060, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ...,
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ...,
        [ 2.449372],
        [ 0.401197]],

       ...,

       [[ 1.121319],
        [ 1.719423],
        ...,
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ...,
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid         (neuroid) MultiIndex
  - neuroid_id      (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr             (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col             (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere      (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion       (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal          (neuroid) object 'Chabo' 'C

In [140]:
assert hvm_stripped_copy.shape == hvm.shape

In [158]:
nanless = lambda da: da.loc[:, da["image_id"]!="nan"]

In [159]:
assert all(nanless(hvm_stripped_copy)["image_id"].values == nanless(hvm)["image_id"].values)
# assert all(hvm_stripped_copy["background_id"].values == hvm["background_id"].values)
assert all(nanless(hvm_stripped_copy)["object"].values == nanless(hvm)["object"].values)
# assert all(hvm_stripped_copy["variation"].values == hvm["variation"].values)

In [148]:
hvm_stripped_copy["object"].values[hvm_stripped_copy["object"].values != hvm["object"].values]

array([nan, nan, nan, ..., nan, nan, nan], dtype=object)

In [157]:
hvm.loc[:, hvm["image_id"]!="nan"]
# hvm["background_id"]!="nan"

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 268800, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ...,
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ...,
        [ 2.449372],
        [ 0.401197]],

       ...,

       [[ 1.121319],
        [ 1.719423],
        ...,
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ...,
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal           (neuroid) object 'Chabo' 'Ch

In [11]:
hvm_stripped_copy["image_id"]

<xarray.NeuronRecordingAssembly 'image_id' (presentation: 270060)>
array(['8a72e2bfdb8c267b57232bf96f069374d5b21832',
       '27f69468c9d6019ed0d22b9583c94c5b58198c1c',
       '6af1cbb28aacea6c582faa07e92d8325fa7a29d7', ...,
       'd6a597127092d38ed37bcb19967075698acb35ee',
       'cc975ea997317b74a79b9f5568f8008acdec341e',
       'e35071a43f7a0dafc21b18229ca36f1940c2c567'], dtype=object)
Coordinates:
  * presentation  (presentation) MultiIndex
  - image_id      (presentation) object '8a72e2bfdb8c267b57232bf96f069374d5b21832' ...
  - repetition    (presentation) int64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
  - stimulus      (presentation) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ...

In [14]:
hvm["image_id"]

<xarray.NeuronRecordingAssembly 'image_id' (presentation: 270060)>
array(['8a72e2bfdb8c267b57232bf96f069374d5b21832',
       '27f69468c9d6019ed0d22b9583c94c5b58198c1c',
       '6af1cbb28aacea6c582faa07e92d8325fa7a29d7', ...,
       'd6a597127092d38ed37bcb19967075698acb35ee',
       'cc975ea997317b74a79b9f5568f8008acdec341e',
       'e35071a43f7a0dafc21b18229ca36f1940c2c567'], dtype=object)
Coordinates:
  * presentation     (presentation) MultiIndex
  - ryz_semantic     (presentation) float64 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 ...
  - object           (presentation) object 'car_astra' 'table3' 'face2' ...
  - variation        (presentation) object 'V0' 'V0' 'V0' 'V0' 'V0' 'V0' ...
  - image_id         (presentation) object '8a72e2bfdb8c267b57232bf96f069374d5b21832' ...
  - image_file_name  (presentation) object 'astra_rx+00.000_ry+00.000_rz+00.000_tx+00.000_ty+00.000_s+01.000_ecd40f3f6d7a4d6d88134d648884e0b9b364efc9_256x256.png' ...
  - rxy_semantic     (presentation) float64 90.0 -0.0 -0.0 

In [138]:
all(hvm_stripped_copy["image_id"].values == hvm["image_id"].values)

True

In [139]:
all(df_stimulus["image_id"].values == hvm["image_id"].values)

True

In [49]:
merged = pd.merge(hvm_stripped_copy.indexes["presentation"].to_frame(), df_images, on="image_id", how="left")
merged

image_id  repetition  stimulus  \
0       8a72e2bfdb8c267b57232bf96f069374d5b21832           0         0   
1       27f69468c9d6019ed0d22b9583c94c5b58198c1c           0         1   
2       6af1cbb28aacea6c582faa07e92d8325fa7a29d7           0         2   
3       d0f7a45b377d4920c3466ec7a20dce9437a150d6           0         3   
4       d4c3b4d4aefd29fd168a2c3c9a9962d99653a715           0         4   
5       c6fb4f35719f0f205f5ad65f4fd2794212c5d139           0         5   
6       ae2b8aac003c867a772647197dcd3c050b75a06e           0         6   
7       a7a31e65e2770c7a503988835c24aeab689abf47           0         7   
8       09d2924723bc4677df666072b6e25e988d5f0668           0         8   
9       1df484a50ff7fbd85112990b7f8fe616c49adb28           0         9   
10      e134c3d8fa8be11c8eb0b8d55e7f534286f44736           0        10   
11      6997bb3d5bef2f6f9d6cfbdcaab1444680a44cb0           0        11   
12      fbef152524d2e593206fd976afde5e0506f477a8           0        12   
13      a17db26a610f96215d94cd673fd982c5bb3fd524           0        13   
14      41e376452bcb4a61646304b4fd397f11e329ebb2           0        14   
15      36b1652f43aedf23e39f351fd931ab0cb4c410b5           0        15   
16      6a8b93cd59587cc2969a126361bce879774e7f4f           0        16   
17      05954905d976ab1cf247c49fc31e534a8a047ba1           0        17   
18      97757502b8c2e32e47a79a266f2da46bbb7165d1           0        18   
19      45b221ea1ed093c991ba6503c57093f6bea2c9d7           0        19   
20      f680c591330f26793f4de603e26cc584ae19ddb2           0        20   
21      a2de393bdfbaaa69500cc1b0d1bfe0f37c6459e1           0        21   
22      f4fe19dc937fb33d9439fc99f4ea17fc76591e36           0        22   
23      dd8ff3ddeac872a646b02b8fdcf286c87cdd7720           0        23   
24      3d31939c0fbbb695d865f3e010d9860b65c674f2           0        24   
25      88429363542db8c918d7112a7335fcca62966a3e           0        25   
26      1d832e0abdd6266fb3dcacfa05df1725d6b08fb7           0        26   
27      b54f9e7fbc9f49bb60f6d24aa9e90b7623a4b42d           0        27   
28      6e2ddadd2ca093f7638282e4851b60d5b87b8ca4           0        28   
29      a533e519b553cdf360ae134f7c9f161134ddaf00           0        29   
...                                          ...         ...       ...   
270030  fd135a1c5e2b157b4557ef8473681ca6d03b0188          46      2540   
270031  6b87003f02400681dc545c7cd57cde747c1cb98a          46      2541   
270032  a051580c645ed432381d24beb6e93ee7952c8334          46      2542   
270033  a8648457a08c568c907c68d058e2d33bb276a71e          46      2543   
270034  241a33fd5221263ac3d350bd82ddeab2d0104eab          46      2544   
270035  81445f4ea46ae937d1b94f93f5e9a475dc6e0817          46      2545   
270036  51ba24371f3c0683da1978d332184732bbec5b96          46      2546   
270037  88f954276bb53915429cc2d117e57c08bc8aaddd          46      2547   
270038  d2af56088e557fbafc9815e9a7486f3efe61823e          46      2548   
270039  d4dd9a086994a89bf6e2d32efab254bdd4648888          46      2549   
270040  30912859b0dfac9c6531061a796fb96f16510fa8          46      2550   
270041  8b85fdd6295e9fa10c1230edd6ea63a038ceb15e          46      2551   
270042  518d256ccedbcda049049c1183bc30ff2aa93258          46      2552   
270043  98cc0d8f063fae1b0c22645f384875ec0f73212c          46      2553   
270044  fd18b1f8ca6d961c163aa56772d813f6cba28336          46      2554   
270045  5650c755edcbeb39a1d8b848128bd52e97a3c2c2          46      2555   
270046  10a6a9b7b8a5a83708417f4feebe7f12eee6ecec          46      2556   
270047  d15aa059b0180b200fb82fb8039247c3b53f9d66          46      2557   
270048  bb2ca2aeb9a7996ef849aeca2388fece5d66dd58          46      2558   
270049  af8325d2d77b8475a00eb9a5296689adb4a8f39b          46      2559   
270050  5cbd24a0ac1881551f356940236e021bd29cd1de          46      2560   
270051  feef7d8cf74ce5f8a8d0612e015e0de363587e93          46      2561   
270052  6f61f7e3130d2fef3deeb310e08a927521cb

In [ ]:
hvm_nanless = hvm.loc[:, hvm["image_id"] != "nan", :]

In [59]:
assert merged.shape[0] == hvm_stripped_copy.shape[1]
assert all(merged["image_id"] == hvm["image_id"].values)
assert all(merged["background_id"] == hvm["background_id"].values)
assert all(merged["object"] == hvm["object"].values)
assert all(merged["variation"] == hvm["variation"].values)
# for col in ["image_id", "background_id", "object", "variation"]:
#     assert all(merged[col] == hvm[col].values)

AssertionError: 

In [66]:
assert all(merged["image_id"] == hvm_stripped_copy["image_id"].values)

In [69]:
merged[["background_id"]]

background_id
0       ecd40f3f6d7a4d6d88134d648884e0b9b364efc9
1       006d66c207c6417574f62f0560c6b2b40a9ec5a1
2       3b3c1d65865028d0fad0b0bf8f305098db717e7f
3       687ade2f9ee4d52af9705865395471a24ba38d5f
4       724e5703cc42aa2c3ff135e3508038a90e4ebcb3
5       d6399fdb5cfe58a1c1908762cfe82406e2510231
6       7b44fb43755d315da8e94d73a1ab04e5db592a04
7       03f46b6acdb2fc42f934c5ef67792026de49d530
8       0e3b948ff7c95fcdd6bd07dc0d74b8e2c6ea0e25
9       2164801f3646e5e82eaa4373f8d249ce17edf1ac
10      a7822b52b3d9b276234e9ef3d78e9e1a2aa0eeb9
11      87b9dcc6b79133dc602f3a1c3f9a7cbbbb3a6456
12      fa3aff9af6b31c0527d07d84a9f49b95f265f1fb
13      8f388437a015e5358e27dad6f0d60e023db40e60
14      0c0d7402273188a7ed2d91dbef4baf75554c2017
15      087d94504c098c5ebf0ad52164ffd70020644e6e
16      8001b24ed42c36be17da6ca4213b4d8be30be63a
17      90f464d4725214ddae0e9d2dd2e759db0561cb94
18      23957035c1e23cd4e8480b9aae74eca53837d835
19      78944dce513d8a9bd023e4b4e0e7c53f69437ea6
20      ee94a3eb3df3de74988b6021a4a4644b6a8349a2
21      824c7a6bd9bd2d9db1a239a90330ee4547249439
22      0ab2c4be3b78a75e6e4b9cceac1b982e14546335
23      4252b5aec4714cde9351afcc18f9c4f1a7b260ae
24      eb58d84e32e97638191725980511005bc3c4298f
25      9bafe6f72571fcf11f6fc8f72bbc1f5bc2f8c0e0
26      f0ec7e27681c3c7e8ea8e00ae387a8ab346c1ea2
27      4647133f7784fbd40525ea113de132186f16667e
28      36d608bfa09d2d58f42f1cd12a27a2b80a3b8d02
29      840b0badda8be10e1e3d5eff5cedce384f8021bc
...                                          ...
270030  3f072352f8336529aba839aa86fe0114d11886fc
270031  771e5ab1f204905bf03d06936b01bb5f4de92788
270032  f0cd72ef854ffa497fc53ef0e179bce45e8c2743
270033  f2e18d3ca4f6e9899a519b5d74d2be7c4577a401
270034  6dec52041309894f4d4da45448fc6c9a4cd4ba87
270035  b1a3abb743a6380929584173dcbbb5956bc0d216
270036  2bc87202ff78a3f635e52fc82bf5bad487aaa1bc
270037  828850cf3e0695ec1d4d32219904cf5e199210e2
270038  cb40eea4d91e603380e46852251ad642dfd0ba75
270039  f5cd0d63fecaea3648437bb85522e5b7ec5ccaf6
270040  9b87c8be1440ce9626bcfe656700ff3ac8f909fe
270041  62a27decc64031d42ac8b683fb1e8c0ac0b616cf
270042  57102e072f4cac897d8089085ca932a40a1aa1d5
270043  f934a940602d18a719e8a3026c201301958142af
270044  5e13ca12b89cd9631656c619a3a0c88b69b75b8e
270045  4a257824a10bdae247bd9d6e18ccdf0cd9c3fe1b
270046  20a8031d6c172b2f92dbd5d08b41d5dcd3f4d21b
270047  5068064aee7a1831c3a5fe0f023b05cffca511e3
270048  d6e2227592c00e5fa2607781d8a5096854058f7b
270049  52b8677d036765ba6c05d8035b641e3c55993f9a
270050  5a38b191f3aaa9592b8909777441e9dab3913997
270051  fc7f1dc814e56de2c6e1a715a83c9f9a70b3a1f5
270052  9ce9ffa3b4e08ee91c5b5488dd80a62973e7e280
270053  f1bed88aa0fa49ce67ca15a82eb37c003e95cb56
270054  0405dd6bf7747d33a030f46c86eabda0bd95e00a
270055  f0e2cf213ecf2fa5b8f1d733bd80ba3037f9042d
270056  821565cb10250ce762b8c594185fc810f52d38ea
270057  524d21ed6255411c1f1531e075b1098eb2cda2e6
270058  2363c8c3859603ee9db7f83dd7ba5b6989154258
270059  a7fc954d2bd08fc2c4d3ade347f41a03a5850131

[270060 rows x 1 columns]

In [68]:
hvm["background_id"]

<xarray.NeuronRecordingAssembly 'background_id' (presentation: 270060)>
array(['ecd40f3f6d7a4d6d88134d648884e0b9b364efc9',
       '006d66c207c6417574f62f0560c6b2b40a9ec5a1',
       '3b3c1d65865028d0fad0b0bf8f305098db717e7f', ...,
       '524d21ed6255411c1f1531e075b1098eb2cda2e6',
       '2363c8c3859603ee9db7f83dd7ba5b6989154258',
       'a7fc954d2bd08fc2c4d3ade347f41a03a5850131'], dtype=object)
Coordinates:
  * presentation     (presentation) MultiIndex
  - ryz_semantic     (presentation) float64 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 ...
  - object           (presentation) object 'car_astra' 'table3' 'face2' ...
  - variation        (presentation) object 'V0' 'V0' 'V0' 'V0' 'V0' 'V0' ...
  - image_id         (presentation) object '8a72e2bfdb8c267b57232bf96f069374d5b21832' ...
  - image_file_name  (presentation) object 'astra_rx+00.000_ry+00.000_rz+00.000_tx+00.000_ty+00.000_s+01.000_ecd40f3f6d7a4d6d88134d648884e0b9b364efc9_256x256.png' ...
  - rxy_semantic     (presentation) float64 90.0 -0.0 

In [30]:
merged.shape, hvm.shape

((268800, 18), (296, 270060, 1))

In [37]:
hvm.sel(image_id="nan")

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 1260, time_bin: 1)>
array([[[ 1.181566],
        [ 1.928658],
        ...,
        [ 0.567935],
        [ 1.305603]],

       [[-0.04668 ],
        [ 0.292777],
        ...,
        [-0.281528],
        [ 1.403533]],

       ...,

       [[ 2.317528],
        [-0.07489 ],
        ...,
        [-0.599595],
        [-1.093769]],

       [[-0.518903],
        [-2.139034],
        ...,
        [ 0.360143],
        [-0.924476]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal           (neuroid) object 'Chabo' 'Chab

In [42]:
hvm.loc[:, hvm["image_id"] != "nan", :]
# hvm["image_id"] != "nan"

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 268800, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ...,
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ...,
        [ 2.449372],
        [ 0.401197]],

       ...,

       [[ 1.121319],
        [ 1.719423],
        ...,
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ...,
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal           (neuroid) object 'Chabo' 'Ch

In [85]:
df_dummy_value = pd.DataFrame({
    "image_id": list("ABCDE")*5, 
    "value": [i*10**j for j in range(5) for i in range(1, 6)]})
df_dummy_value

image_id  value
0         A      1
1         B      2
2         C      3
3         D      4
4         E      5
5         A     10
6         B     20
7         C     30
8         D     40
9         E     50
10        A    100
11        B    200
12        C    300
13        D    400
14        E    500
15        A   1000
16        B   2000
17        C   3000
18        D   4000
19        E   5000
20        A  10000
21        B  20000
22        C  30000
23        D  40000
24        E  50000

In [81]:
df_dummy_meta = pd.DataFrame({
    "image_id": list("ABCDE"), 
    "object": ["orange", "apple", "banana", "pear", "grapefruit"]})
df_dummy_meta

image_id      object
0        A      orange
1        B       apple
2        C      banana
3        D        pear
4        E  grapefruit

In [86]:
df_dummy_value["object"] = df_dummy_value.merge(df_dummy_meta, on="image_id", how="left")["object"]
df_dummy_value

image_id  value      object
0         A      1      orange
1         B      2       apple
2         C      3      banana
3         D      4        pear
4         E      5  grapefruit
5         A     10      orange
6         B     20       apple
7         C     30      banana
8         D     40        pear
9         E     50  grapefruit
10        A    100      orange
11        B    200       apple
12        C    300      banana
13        D    400        pear
14        E    500  grapefruit
15        A   1000      orange
16        B   2000       apple
17        C   3000      banana
18        D   4000        pear
19        E   5000  grapefruit
20        A  10000      orange
21        B  20000       apple
22        C  30000      banana
23        D  40000        pear
24        E  50000  grapefruit

In [95]:
da_dummy_value = xr.DataArray(data=df_dummy_value["value"], dims=("value"), coords={
    "image_id": ("value", df_dummy_value["image_id"]),
    "value_id": ("value", df_dummy_value.index)
})
da_dummy_value

<xarray.DataArray 'value' (value: 25)>
array([    1,     2,     3,     4,     5,    10,    20,    30,    40,    50,
         100,   200,   300,   400,   500,  1000,  2000,  3000,  4000,  5000,
       10000, 20000, 30000, 40000, 50000])
Coordinates:
    image_id  (value) object 'A' 'B' 'C' 'D' 'E' 'A' 'B' 'C' 'D' 'E' 'A' 'B' ...
    value_id  (value) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 ...
Dimensions without coordinates: value

In [117]:
da_dummy_value["image_id"]

<xarray.DataArray 'image_id' (value: 25)>
array(['A', 'B', 'C', 'D', 'E', 'A', 'B', 'C', 'D', 'E', 'A', 'B', 'C', 'D',
       'E', 'A', 'B', 'C', 'D', 'E', 'A', 'B', 'C', 'D', 'E'], dtype=object)
Coordinates:
    image_id  (value) object 'A' 'B' 'C' 'D' 'E' 'A' 'B' 'C' 'D' 'E' 'A' 'B' ...
    value_id  (value) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 ...
Dimensions without coordinates: value

In [122]:
da_dummy_value.set_index(append=True, inplace=True, value=["image_id", "value_id"])
da_dummy_value

<xarray.DataArray 'value' (value: 25)>
array([    1,     2,     3,     4,     5,    10,    20,    30,    40,    50,
         100,   200,   300,   400,   500,  1000,  2000,  3000,  4000,  5000,
       10000, 20000, 30000, 40000, 50000])
Coordinates:
  * value     (value) MultiIndex
  - image_id  (value) object 'A' 'B' 'C' 'D' 'E' 'A' 'B' 'C' 'D' 'E' 'A' 'B' ...
  - value_id  (value) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 ...

In [125]:
mi = da_dummy_value.indexes["value"]
mi

MultiIndex(levels=[['A', 'B', 'C', 'D', 'E'], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]],
           labels=[[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]],
           names=['image_id', 'value_id'])

In [126]:
mi.to_frame()

image_id  value_id
image_id value_id                   
A        0               A         0
B        1               B         1
C        2               C         2
D        3               D         3
E        4               E         4
A        5               A         5
B        6               B         6
C        7               C         7
D        8               D         8
E        9               E         9
A        10              A        10
B        11              B        11
C        12              C        12
D        13              D        13
E        14              E        14
A        15              A        15
B        16              B        16
C        17              C        17
D        18              D        18
E        19              E        19
A        20              A        20
B        21              B        21
C        22              C        22
D        23              D        23
E        24              E        24

In [128]:
mi.to_frame().merge(df_dummy_meta, on="image_id", how="left")

image_id  value_id      object
0         A         0      orange
1         B         1       apple
2         C         2      banana
3         D         3        pear
4         E         4  grapefruit
5         A         5      orange
6         B         6       apple
7         C         7      banana
8         D         8        pear
9         E         9  grapefruit
10        A        10      orange
11        B        11       apple
12        C        12      banana
13        D        13        pear
14        E        14  grapefruit
15        A        15      orange
16        B        16       apple
17        C        17      banana
18        D        18        pear
19        E        19  grapefruit
20        A        20      orange
21        B        21       apple
22        C        22      banana
23        D        23        pear
24        E        24  grapefruit

In [129]:
mi.to_frame().merge(df_dummy_meta, on="image_id", how="left")["object"]

0         orange
1          apple
2         banana
3           pear
4     grapefruit
5         orange
6          apple
7         banana
8           pear
9     grapefruit
10        orange
11         apple
12        banana
13          pear
14    grapefruit
15        orange
16         apple
17        banana
18          pear
19    grapefruit
20        orange
21         apple
22        banana
23          pear
24    grapefruit
Name: object, dtype: object

In [131]:
da_dummy_value["object"] = ("value", da_dummy_value.indexes["value"].to_frame().merge(df_dummy_meta, on="image_id", how="left")["object"])
da_dummy_value

<xarray.DataArray 'value' (value: 25)>
array([    1,     2,     3,     4,     5,    10,    20,    30,    40,    50,
         100,   200,   300,   400,   500,  1000,  2000,  3000,  4000,  5000,
       10000, 20000, 30000, 40000, 50000])
Coordinates:
  * value     (value) MultiIndex
  - image_id  (value) object 'A' 'B' 'C' 'D' 'E' 'A' 'B' 'C' 'D' 'E' 'A' 'B' ...
  - value_id  (value) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 ...
    object    (value) object 'orange' 'apple' 'banana' 'pear' 'grapefruit' ...

In [132]:
da_dummy_value.to_dataframe()

object  value
image_id value_id                   
A        0             orange      1
B        1              apple      2
C        2             banana      3
D        3               pear      4
E        4         grapefruit      5
A        5             orange     10
B        6              apple     20
C        7             banana     30
D        8               pear     40
E        9         grapefruit     50
A        10            orange    100
B        11             apple    200
C        12            banana    300
D        13              pear    400
E        14        grapefruit    500
A        15            orange   1000
B        16             apple   2000
C        17            banana   3000
D        18              pear   4000
E        19        grapefruit   5000
A        20            orange  10000
B        21             apple  20000
C        22            banana  30000
D        23              pear  40000
E        24        grapefruit  50000