In [2]:
import numpy as np
import xarray as xr

In [3]:
da1 = xr.DataArray(np.random.randn(2, 3), [('x', ['a', 'b']), ('y', [10, 20, 30])])
da1

<xarray.DataArray (x: 2, y: 3)>
array([[-0.677337, -0.777142,  0.916852],
       [-0.31313 ,  0.341775, -0.416006]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30

In [4]:
da2 = xr.DataArray(np.random.randn(2, 3), [('x', ['c', 'd']), ('y', [40, 50, 60])])
da2

<xarray.DataArray (x: 2, y: 3)>
array([[-0.665198,  0.634057, -0.003932],
       [ 0.383107,  0.828298,  0.971749]])
Coordinates:
  * x        (x) <U1 'c' 'd'
  * y        (y) int64 40 50 60

In [5]:
da3 = xr.DataArray(np.random.randn(2, 2), [('x', ['b', 'c']), ('y', [30, 40])])
da3

<xarray.DataArray (x: 2, y: 2)>
array([[ 0.648664, -1.197077],
       [-1.234978, -0.125411]])
Coordinates:
  * x        (x) <U1 'b' 'c'
  * y        (y) int64 30 40

In [6]:
xr.align(da1, da2, join="outer")

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


(<xarray.DataArray (x: 4, y: 6)>
 array([[-0.677337, -0.777142,  0.916852,       nan,       nan,       nan],
        [-0.31313 ,  0.341775, -0.416006,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60, <xarray.DataArray (x: 4, y: 6)>
 array([[      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan, -0.665198,  0.634057, -0.003932],
        [      nan,       nan,       nan,  0.383107,  0.828298,  0.971749]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60)

In [7]:
xr.align(da1, da2, da3, join="outer")

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


(<xarray.DataArray (x: 4, y: 6)>
 array([[-0.677337, -0.777142,  0.916852,       nan,       nan,       nan],
        [-0.31313 ,  0.341775, -0.416006,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60, <xarray.DataArray (x: 4, y: 6)>
 array([[      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan, -0.665198,  0.634057, -0.003932],
        [      nan,       nan,       nan,  0.383107,  0.828298,  0.971749]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60, <xarray.DataArray (x: 4, y: 6)>
 array([[      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,  

In [9]:
xr.concat(xr.align(da1, da2, da3, join="outer"), dim="y")

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


<xarray.DataArray (x: 4, y: 18)>
array([[-0.677337, -0.777142,  0.916852,       nan,       nan,       nan,
              nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan,       nan,       nan,       nan],
       [-0.31313 ,  0.341775, -0.416006,       nan,       nan,       nan,
              nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,  0.648664, -1.197077,       nan,       nan],
       [      nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan, -0.665198,  0.634057, -0.003932,
              nan,       nan, -1.234978, -0.125411,       nan,       nan],
       [      nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan,  0.383107,  0.828298,  0.971749,
              nan,       nan,       nan,       nan,       nan,       nan]])
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int6

In [10]:
xr.merge([da1, da2, da3])

ValueError: unable to convert unnamed DataArray to a Dataset without providing an explicit name

In [13]:
xr.merge(xr.align(da1, da2, da3, join="outer"))

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


ValueError: unable to convert unnamed DataArray to a Dataset without providing an explicit name

In [11]:
da1.combine_first(da2)

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


<xarray.DataArray (x: 4, y: 6)>
array([[-0.677337, -0.777142,  0.916852,       nan,       nan,       nan],
       [-0.31313 ,  0.341775, -0.416006,       nan,       nan,       nan],
       [      nan,       nan,       nan, -0.665198,  0.634057, -0.003932],
       [      nan,       nan,       nan,  0.383107,  0.828298,  0.971749]])
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int64 10 20 30 40 50 60

In [12]:
da1.combine_first(da3)

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


<xarray.DataArray (x: 3, y: 4)>
array([[-0.677337, -0.777142,  0.916852,       nan],
       [-0.31313 ,  0.341775, -0.416006, -1.197077],
       [      nan,       nan, -1.234978, -0.125411]])
Coordinates:
  * x        (x) object 'a' 'b' 'c'
  * y        (y) int64 10 20 30 40

In [14]:
da1.name = "da1"
da2.name = "da2"
da3.name = "da3"

In [15]:
xr.merge([da1, da2, da3])

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


<xarray.Dataset>
Dimensions:  (x: 4, y: 6)
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int64 10 20 30 40 50 60
Data variables:
    da1      (x, y) float64 -0.6773 -0.7771 0.9169 nan nan nan -0.3131 ...
    da2      (x, y) float64 nan nan nan nan nan nan nan nan nan nan nan nan ...
    da3      (x, y) float64 nan nan nan nan nan nan nan nan 0.6487 -1.197 ...

In [16]:
da1 != da2

<xarray.DataArray (x: 0, y: 0)>
array([], shape=(0, 0), dtype=bool)
Coordinates:
  * x        (x) object 
  * y        (y) int64 

In [17]:
da1 != da3

<xarray.DataArray (x: 1, y: 1)>
array([[ True]])
Coordinates:
  * x        (x) object 'b'
  * y        (y) int64 30

In [18]:
aligned = xr.align(da1, da2, da3, join="outer")

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


In [19]:
aligned[0] != aligned[1]

<xarray.DataArray (x: 4, y: 6)>
array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int64 10 20 30 40 50 60

In [20]:
aligned[0] != aligned[2]

<xarray.DataArray (x: 4, y: 6)>
array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int64 10 20 30 40 50 60

In [22]:
np.nonzero(np.array([True, True, False]))

(array([0, 1]),)

In [23]:
da4 = xr.DataArray([[0.0, np.nan, np.nan], [np.nan, 1.0, np.nan], [np.nan, np.nan, 2.0]], [('x', ['a', 'b', 'c']), ('y', [10, 20, 30])])
da4

<xarray.DataArray (x: 3, y: 3)>
array([[ 0., nan, nan],
       [nan,  1., nan],
       [nan, nan,  2.]])
Coordinates:
  * x        (x) <U1 'a' 'b' 'c'
  * y        (y) int64 10 20 30

In [24]:
da5 = xr.DataArray([[0.1, np.nan, np.nan], [np.nan, 0.2, np.nan], [np.nan, np.nan, 0.3]], [('x', ['c', 'd', 'e']), ('y', [40, 50, 60])])
da5

<xarray.DataArray (x: 3, y: 3)>
array([[0.1, nan, nan],
       [nan, 0.2, nan],
       [nan, nan, 0.3]])
Coordinates:
  * x        (x) <U1 'c' 'd' 'e'
  * y        (y) int64 40 50 60

In [25]:
xr.align(da4, da5, join="outer")

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


(<xarray.DataArray (x: 5, y: 6)>
 array([[ 0., nan, nan, nan, nan, nan],
        [nan,  1., nan, nan, nan, nan],
        [nan, nan,  2., nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd' 'e'
   * y        (y) int64 10 20 30 40 50 60, <xarray.DataArray (x: 5, y: 6)>
 array([[nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, 0.1, nan, nan],
        [nan, nan, nan, nan, 0.2, nan],
        [nan, nan, nan, nan, nan, 0.3]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd' 'e'
   * y        (y) int64 10 20 30 40 50 60)

In [27]:
dims = ("x", "y")
coords_d = {"x": ("lower",  "upper"), "y": ("linear", "exponential")}

data6 = [[1.0, np.nan, np.nan], [np.nan, 2.0, np.nan], [np.nan, np.nan, 3.0]]
coords6 = {
    "lower": ("x", ["a", "b", "c"]), 
    "upper": ("x", ["A", "B", "C"]), 
    "linear": ("y", [10, 20, 30]), 
    "exponential": ("y", [10, 100, 1000])
}
da6 = xr.DataArray(data=data6, dims=dims, coords=coords6)

data7 = [[0.1, np.nan, np.nan], [np.nan, 0.2, np.nan], [np.nan, np.nan, 0.3]]
coords7 = {
    "lower": ("x", ["c", "d", "e"]), 
    "upper": ("x", ["C", "D", "E"]), 
    "linear": ("y", [40, 50, 60]), 
    "exponential": ("y", [10000, 100000, 1000000])
}
da7 = xr.DataArray(data=data7, dims=dims, coords=coords7)

for da in (da6, da7):
    da.set_index(append=True, inplace=True, **coords_d)

(da6, da7)

(<xarray.DataArray (x: 3, y: 3)>
 array([[ 1., nan, nan],
        [nan,  2., nan],
        [nan, nan,  3.]])
 Coordinates:
   * x            (x) MultiIndex
   - lower        (x) object 'a' 'b' 'c'
   - upper        (x) object 'A' 'B' 'C'
   * y            (y) MultiIndex
   - linear       (y) int64 10 20 30
   - exponential  (y) int64 10 100 1000, <xarray.DataArray (x: 3, y: 3)>
 array([[0.1, nan, nan],
        [nan, 0.2, nan],
        [nan, nan, 0.3]])
 Coordinates:
   * x            (x) MultiIndex
   - lower        (x) object 'c' 'd' 'e'
   - upper        (x) object 'C' 'D' 'E'
   * y            (y) MultiIndex
   - linear       (y) int64 40 50 60
   - exponential  (y) int64 10000 100000 1000000)

In [28]:
xr.align(da6, da7, join="outer")

/braintree/home/jjpr/anaconda3/envs/mkgu_packaging/lib/python3.6/site-packages/xarray/core/dtypes.py:23: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if np.issubdtype(dtype, float):


(<xarray.DataArray (x: 5, y: 6)>
 array([[ 1., nan, nan, nan, nan, nan],
        [nan,  2., nan, nan, nan, nan],
        [nan, nan,  3., nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan]])
 Coordinates:
   * x            (x) MultiIndex
   - lower        (x) object 'a' 'b' 'c' 'd' 'e'
   - upper        (x) object 'A' 'B' 'C' 'D' 'E'
   * y            (y) MultiIndex
   - linear       (y) int64 10 20 30 40 50 60
   - exponential  (y) int64 10 100 1000 10000 100000 1000000,
 <xarray.DataArray (x: 5, y: 6)>
 array([[nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, 0.1, nan, nan],
        [nan, nan, nan, nan, 0.2, nan],
        [nan, nan, nan, nan, nan, 0.3]])
 Coordinates:
   * x            (x) MultiIndex
   - lower        (x) object 'a' 'b' 'c' 'd' 'e'
   - upper        (x) object 'A' 'B' 'C' 'D' 'E'
   * y            (y) MultiIndex
   - linear       (y) int64 10 20 30 40 50 60
   - exponential  (y) 

In [36]:
da6_file = "xarray_align_debug_da6.nc"
da6.to_netcdf(da6_file)
da6_reloaded = xr.open_dataarray(da6_file)

da7_file = "xarray_align_debug_da7.nc"
da7.to_netcdf(da7_file)
da7_reloaded = xr.open_dataarray(da7_file)

(da6_reloaded, da7_reloaded)

NotImplementedError: variable 'x' is a MultiIndex, which cannot yet be serialized to netCDF files (https://github.com/pydata/xarray/issues/1077). Use reset_index() to convert MultiIndex levels into coordinate variables instead.

In [33]:
da_loaded = xr.open_dataarray("/braintree/data2/active/users/jjpr/mkgu_packaging/crcns/v2-1/V2Data1/DGrat/data.nc")
non_nan = np.nonzero(~np.isnan(da_loaded))
(da_loaded.shape, non_nan.values.shape)

((96000, 10), (2, 1772))

In [35]:
da_loaded.load()
non_nan_after_load = np.nonzero(~np.isnan(da_loaded))
(da_loaded.shape, non_nan_after_load.values.shape)

((96000, 10), (2, 1772))