In [1]:
import os

In [2]:
import shutil

In [41]:
from pathlib import Path

In [18]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import xarray as xr

In [5]:
import brainio_collection

In [6]:
from brainio_collection.knownfile import KnownFile as kf

In [7]:
target_dir = "/Users/jjpr/dev/brainio_contrib/tests/images"

In [ ]:
stim = brainio_collection.get_stimulus_set("dicarlo.hvm")
stim

In [ ]:
samp = stim[stim["variation"] == 0].sample(n=25)
samp

In [ ]:
samp["image_current_local_file_path"] = [samp.get_image(x) for x in samp["image_id"]]
samp

In [ ]:
samp["sha1"] = [kf(im).sha1 for im in samp["image_current_local_file_path"]]
samp

In [ ]:
samp["image_source_local_file_path"] = samp["image_current_local_file_path"]
samp["image_target_local_file_path"] = [os.path.join(target_dir, im.image_id + ".png") for im in samp.itertuples()]
samp

In [ ]:
for im in samp.itertuples():
  shutil.copy(im.image_source_local_file_path, im.image_target_local_file_path)

In [ ]:
image_file_names = [im.image_id + ".png" for im in samp.itertuples()]
out_df = pd.DataFrame({
  "image_id": samp["image_id"], 
  "image_current_relative_file_path": image_file_names, 
  "image_path_within_store": image_file_names,
  "object_name": samp["object_name"],
  "category_name": samp["category_name"],
  "size": samp["size"]
})
out_df

In [8]:
target_csv = os.path.join(target_dir, "test_images.csv")
target_csv

'/Users/jjpr/dev/brainio_contrib/tests/images/test_images.csv'

In [ ]:
out_df.to_csv(target_csv, index=False)

In [9]:
proto = pd.read_csv(target_csv)
proto

image_id  \
0   b713c093a9135539f1fdd0b92c44f59688267561   
1   9d89aedf86af6292d4d6fe3774a51c92fb715c4e   
2   11bfd22097d9c511621ef17b2c13067dc1cd7352   
3   398ece9ff10d90e31c39e0b7625454d81fc19f8d   
4   c4fac169f2c9ce65d4647435e1d720ea25554dfe   
5   2ea3bb4fb4212f49f1382a938351d3c2e8e0a652   
6   cf1f1948b5e55815a11b72c52831275bababaeea   
7   4e05f442f98dceb778e7de1f2d0f700241461756   
8   2371c02dcd0b562d3dd7cfb13123f7d426cf4810   
9   cc67fe89474be6c5ae653843a75d9ed0b343ca52   
10  5546dc0575a1e6477db5f4accd1d17184deb405b   
11  b64a713676ad771e355fe0cad98121f1cb329d92   
12  2970df86fb9706eb1ef066a7120049eb7bb8656e   
13  79d8e812eae9ecf647eb1eff72d613dff34b1062   
14  ac1db6c2528dd94f07c1ae56b404d73995b5329f   
15  d5685a6afd20ea9cd27444fb14a14ed0f2036a63   
16  a533e519b553cdf360ae134f7c9f161134ddaf00   
17  bffb5a5531aabefe3a9f0eee48963e1dbfc2f5f2   
18  a7792c8a467907240ca8cd98fa51cf768311e398   
19  fd1c8070be2eaf90ee17bed9094e9bb06eb7bb4e   
20  48c621bed18d56770d77b061e01ca33b4548f539   
21  fe4f9a92c45af3487323f2f145d2e49594b61f33   
22  c33a74c58c05433d6ce418cdfc5a2b2edd5b72dc   
23  3a2e8aeaae50f81d1d4fc716969bd2c8e169b9d9   
24  36db24ff49d1e53a12af349c465fc32592168b4b   

                image_current_relative_file_path  \
0   b713c093a9135539f1fdd0b92c44f59688267561.png   
1   9d89aedf86af6292d4d6fe3774a51c92fb715c4e.png   
2   11bfd22097d9c511621ef17b2c13067dc1cd7352.png   
3   398ece9ff10d90e31c39e0b7625454d81fc19f8d.png   
4   c4fac169f2c9ce65d4647435e1d720ea25554dfe.png   
5   2ea3bb4fb4212f49f1382a938351d3c2e8e0a652.png   
6   cf1f1948b5e55815a11b72c52831275bababaeea.png   
7   4e05f442f98dceb778e7de1f2d0f700241461756.png   
8   2371c02dcd0b562d3dd7cfb13123f7d426cf4810.png   
9   cc67fe89474be6c5ae653843a75d9ed0b343ca52.png   
10  5546dc0575a1e6477db5f4accd1d17184deb405b.png   
11  b64a713676ad771e355fe0cad98121f1cb329d92.png   
12  2970df86fb9706eb1ef066a7120049eb7bb8656e.png   
13  79d8e812eae9ecf647eb1eff72d613dff34b1062.png   
14  ac1db6c2528dd94f07c1ae56b404d73995b5329f.png   
15  d5685a6afd20ea9cd27444fb14a14ed0f2036a63.png   
16  a533e519b553cdf360ae134f7c9f161134ddaf00.png   
17  bffb5a5531aabefe3a9f0eee48963e1dbfc2f5f2.png   
18  a7792c8a467907240ca8cd98fa51cf768311e398.png   
19  fd1c8070be2eaf90ee17bed9094e9bb06eb7bb4e.png   
20  48c621bed18d56770d77b061e01ca33b4548f539.png   
21  fe4f9a92c45af3487323f2f145d2e49594b61f33.png   
22  c33a74c58c05433d6ce418cdfc5a2b2edd5b72dc.png   
23  3a2e8aeaae50f81d1d4fc716969bd2c8e169b9d9.png   
24  36db24ff49d1e53a12af349c465fc32592168b4b.png   

                         image_path_within_store object_name category_name  \
0   b713c093a9135539f1fdd0b92c44f59688267561.png       ship2         Boats   
1   9d89aedf86af6292d4d6fe3774a51c92fb715c4e.png   airplane2        Planes   
2   11bfd22097d9c511621ef17b2c13067dc1cd7352.png   raspberry        Fruits   
3   398ece9ff10d90e31c39e0b7625454d81fc19f8d.png      chair4        Chairs   
4   c4fac169f2c9ce65d4647435e1d720ea25554dfe.png    elephant       Animals   
5   2ea3bb4fb4212f49f1382a938351d3c2e8e0a652.png       face6         Faces   
6   cf1f1948b5e55815a11b72c52831275bababaeea.png    car_clio          Cars   
7   4e05f442f98dceb778e7de1f2d0f700241461756.png    car_clio          Cars   
8   2371c02dcd0b562d3dd7cfb13123f7d426cf4810.png   raspberry        Fruits   
9   cc67fe89474be6c5ae653843a75d9ed0b343ca52.png       face1         Faces   
10  5546dc0575a1e6477db5f4accd1d17184deb405b.png     gorilla       Animals   
11  b64a713676ad771e355fe0cad98121f1cb329d92.png         dog       Animals   
12  2970df86fb9706eb1ef066a7120049eb7bb8656e.png       ship3         Boats   
13  79d8e812eae9ecf647eb1eff72d613dff34b1062.png       ship5         Boats   
14  ac1db6c2528dd94f07c1ae56b404d73995b5329f.png      table5        Tables   
15  d5685a6afd20ea9cd27444fb14a14ed0f2036a63.png     lioness       Animals   
16  a533e519b553cdf360ae134f7c9f161134ddaf00.png       face0         Faces   
17  bffb5a5531aabefe3a9f0eee48

In [10]:
proto["image_current_local_file_path"] = [os.path.join(target_dir, f) for f in proto["image_current_relative_file_path"]]
proto

image_id  \
0   b713c093a9135539f1fdd0b92c44f59688267561   
1   9d89aedf86af6292d4d6fe3774a51c92fb715c4e   
2   11bfd22097d9c511621ef17b2c13067dc1cd7352   
3   398ece9ff10d90e31c39e0b7625454d81fc19f8d   
4   c4fac169f2c9ce65d4647435e1d720ea25554dfe   
5   2ea3bb4fb4212f49f1382a938351d3c2e8e0a652   
6   cf1f1948b5e55815a11b72c52831275bababaeea   
7   4e05f442f98dceb778e7de1f2d0f700241461756   
8   2371c02dcd0b562d3dd7cfb13123f7d426cf4810   
9   cc67fe89474be6c5ae653843a75d9ed0b343ca52   
10  5546dc0575a1e6477db5f4accd1d17184deb405b   
11  b64a713676ad771e355fe0cad98121f1cb329d92   
12  2970df86fb9706eb1ef066a7120049eb7bb8656e   
13  79d8e812eae9ecf647eb1eff72d613dff34b1062   
14  ac1db6c2528dd94f07c1ae56b404d73995b5329f   
15  d5685a6afd20ea9cd27444fb14a14ed0f2036a63   
16  a533e519b553cdf360ae134f7c9f161134ddaf00   
17  bffb5a5531aabefe3a9f0eee48963e1dbfc2f5f2   
18  a7792c8a467907240ca8cd98fa51cf768311e398   
19  fd1c8070be2eaf90ee17bed9094e9bb06eb7bb4e   
20  48c621bed18d56770d77b061e01ca33b4548f539   
21  fe4f9a92c45af3487323f2f145d2e49594b61f33   
22  c33a74c58c05433d6ce418cdfc5a2b2edd5b72dc   
23  3a2e8aeaae50f81d1d4fc716969bd2c8e169b9d9   
24  36db24ff49d1e53a12af349c465fc32592168b4b   

                image_current_relative_file_path  \
0   b713c093a9135539f1fdd0b92c44f59688267561.png   
1   9d89aedf86af6292d4d6fe3774a51c92fb715c4e.png   
2   11bfd22097d9c511621ef17b2c13067dc1cd7352.png   
3   398ece9ff10d90e31c39e0b7625454d81fc19f8d.png   
4   c4fac169f2c9ce65d4647435e1d720ea25554dfe.png   
5   2ea3bb4fb4212f49f1382a938351d3c2e8e0a652.png   
6   cf1f1948b5e55815a11b72c52831275bababaeea.png   
7   4e05f442f98dceb778e7de1f2d0f700241461756.png   
8   2371c02dcd0b562d3dd7cfb13123f7d426cf4810.png   
9   cc67fe89474be6c5ae653843a75d9ed0b343ca52.png   
10  5546dc0575a1e6477db5f4accd1d17184deb405b.png   
11  b64a713676ad771e355fe0cad98121f1cb329d92.png   
12  2970df86fb9706eb1ef066a7120049eb7bb8656e.png   
13  79d8e812eae9ecf647eb1eff72d613dff34b1062.png   
14  ac1db6c2528dd94f07c1ae56b404d73995b5329f.png   
15  d5685a6afd20ea9cd27444fb14a14ed0f2036a63.png   
16  a533e519b553cdf360ae134f7c9f161134ddaf00.png   
17  bffb5a5531aabefe3a9f0eee48963e1dbfc2f5f2.png   
18  a7792c8a467907240ca8cd98fa51cf768311e398.png   
19  fd1c8070be2eaf90ee17bed9094e9bb06eb7bb4e.png   
20  48c621bed18d56770d77b061e01ca33b4548f539.png   
21  fe4f9a92c45af3487323f2f145d2e49594b61f33.png   
22  c33a74c58c05433d6ce418cdfc5a2b2edd5b72dc.png   
23  3a2e8aeaae50f81d1d4fc716969bd2c8e169b9d9.png   
24  36db24ff49d1e53a12af349c465fc32592168b4b.png   

                         image_path_within_store object_name category_name  \
0   b713c093a9135539f1fdd0b92c44f59688267561.png       ship2         Boats   
1   9d89aedf86af6292d4d6fe3774a51c92fb715c4e.png   airplane2        Planes   
2   11bfd22097d9c511621ef17b2c13067dc1cd7352.png   raspberry        Fruits   
3   398ece9ff10d90e31c39e0b7625454d81fc19f8d.png      chair4        Chairs   
4   c4fac169f2c9ce65d4647435e1d720ea25554dfe.png    elephant       Animals   
5   2ea3bb4fb4212f49f1382a938351d3c2e8e0a652.png       face6         Faces   
6   cf1f1948b5e55815a11b72c52831275bababaeea.png    car_clio          Cars   
7   4e05f442f98dceb778e7de1f2d0f700241461756.png    car_clio          Cars   
8   2371c02dcd0b562d3dd7cfb13123f7d426cf4810.png   raspberry        Fruits   
9   cc67fe89474be6c5ae653843a75d9ed0b343ca52.png       face1         Faces   
10  5546dc0575a1e6477db5f4accd1d17184deb405b.png     gorilla       Animals   
11  b64a713676ad771e355fe0cad98121f1cb329d92.png         dog       Animals   
12  2970df86fb9706eb1ef066a7120049eb7bb8656e.png       ship3         Boats   
13  79d8e812eae9ecf647eb1eff72d613dff34b1062.png       ship5         Boats   
14  ac1db6c2528dd94f07c1ae56b404d73995b5329f.png      table5        Tables   
15  d5685a6afd20ea9cd27444fb14a14ed0f2036a63.png     lioness       Animals   
16  a533e519b553cdf360ae134f7c9f161134ddaf00.png       face0         Faces   
17  bffb5a5531aabefe3a9f0eee48

In [ ]:
del proto["image_current_relative_file_path"]
proto

In [ ]:
proto.columns

In [ ]:
[x for x in proto]

In [11]:
assy_hvm = brainio_collection.get_assembly("dicarlo.Majaj2015")
assy_hvm

/Users/jjpr/dev/brainio_base/brainio_base/assemblies.py:213: FutureWarning: The inplace argument has been deprecated and will be removed in xarray 0.12.0.
  xr_data.set_index(append=True, inplace=True, **coords_d)
/Users/jjpr/anaconda/envs/brainio/lib/python3.7/site-packages/xarray/core/dataset.py:167: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  idx = pd.MultiIndex(labels=labels, levels=levels, names=names)


<xarray.NeuronRecordingAssembly 'dicarlo.Majaj2015' (neuroid: 296, presentation: 268800, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ...,
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ...,
        [ 2.449372],
        [ 0.401197]],

       ...,

       [[ 1.121319],
        [ 1.719423],
        ...,
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ...,
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' ... 'Chabo_L_P_7_6'
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' ... 'P' 'P' 'P' 'P'
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 ... 8 7 8 6 7 5 7 7 6 6
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' ... 'L' 'L' 'L' 'L'
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' ... 'V4' 'V4' 'V4'
  - animal           (neur

In [ ]:
pd.Series(assy_hvm["image_id"]).values in proto["image_id"]

In [ ]:
xr.merge([assy_hvm["image_id"], proto["image_id"]], join="inner")

In [ ]:
assy_hvm.where(assy_hvm["image_id"] in proto["image_id"], drop=True)

In [ ]:
assy_hvm.sel(image_id=assy_hvm["image_id"].values in proto["image_id"])

In [ ]:
proto["image_id"]

In [ ]:
assy_hvm["image_id"]

In [14]:
xr.DataArray(proto)[:,0]

<xarray.DataArray (dim_0: 25)>
array(['b713c093a9135539f1fdd0b92c44f59688267561',
       '9d89aedf86af6292d4d6fe3774a51c92fb715c4e',
       '11bfd22097d9c511621ef17b2c13067dc1cd7352',
       '398ece9ff10d90e31c39e0b7625454d81fc19f8d',
       'c4fac169f2c9ce65d4647435e1d720ea25554dfe',
       '2ea3bb4fb4212f49f1382a938351d3c2e8e0a652',
       'cf1f1948b5e55815a11b72c52831275bababaeea',
       '4e05f442f98dceb778e7de1f2d0f700241461756',
       '2371c02dcd0b562d3dd7cfb13123f7d426cf4810',
       'cc67fe89474be6c5ae653843a75d9ed0b343ca52',
       '5546dc0575a1e6477db5f4accd1d17184deb405b',
       'b64a713676ad771e355fe0cad98121f1cb329d92',
       '2970df86fb9706eb1ef066a7120049eb7bb8656e',
       '79d8e812eae9ecf647eb1eff72d613dff34b1062',
       'ac1db6c2528dd94f07c1ae56b404d73995b5329f',
       'd5685a6afd20ea9cd27444fb14a14ed0f2036a63',
       'a533e519b553cdf360ae134f7c9f161134ddaf00',
       'bffb5a5531aabefe3a9f0eee48963e1dbfc2f5f2',
       'a7792c8a467907240ca8cd98fa51cf768311e398',


In [17]:
sub = assy_hvm.loc[:, assy_hvm["image_id"].isin(proto["image_id"]), :]
sub

<xarray.NeuronRecordingAssembly 'dicarlo.Majaj2015' (neuroid: 296, presentation: 700, time_bin: 1)>
array([[[ 1.928658],
        [ 0.060929],
        ...,
        [-0.623783],
        [ 0.529768]],

       [[ 0.292777],
        [ 1.990058],
        ...,
        [ 0.967823],
        [-0.386514]],

       ...,

       [[ 1.420371],
        [-0.07489 ],
        ...,
        [-1.35632 ],
        [-0.085704]],

       [[ 0.291163],
        [-0.518903],
        ...,
        [ 2.94649 ],
        [-1.835507]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' ... 'Chabo_L_P_7_6'
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' ... 'P' 'P' 'P' 'P'
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 ... 8 7 8 6 7 5 7 7 6 6
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' ... 'L' 'L' 'L' 'L'
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' ... 'V4' 'V4' 'V4'
  - animal           (neuroid

In [19]:
np.unique(sub["object_name"])

array(['airplane1', 'airplane2', 'airplane4', 'airplane6', 'apple',
       'car_clio', 'car_z3', 'chair4', 'chair7', 'dog', 'elephant',
       'face0', 'face1', 'face6', 'gorilla', 'lioness', 'raspberry',
       'ship2', 'ship3', 'ship5', 'table5'], dtype=object)

In [20]:
np.unique(proto["object_name"])

array(['airplane1', 'airplane2', 'airplane4', 'airplane6', 'apple',
       'car_clio', 'car_z3', 'chair4', 'chair7', 'dog', 'elephant',
       'face0', 'face1', 'face6', 'gorilla', 'lioness', 'raspberry',
       'ship2', 'ship3', 'ship5', 'table5'], dtype=object)

In [21]:
sub["image_id"]

<xarray.NeuronRecordingAssembly 'image_id' (presentation: 700)>
array(['a533e519b553cdf360ae134f7c9f161134ddaf00',
       '4e05f442f98dceb778e7de1f2d0f700241461756',
       'a7792c8a467907240ca8cd98fa51cf768311e398', ...,
       'd5685a6afd20ea9cd27444fb14a14ed0f2036a63',
       'c4fac169f2c9ce65d4647435e1d720ea25554dfe',
       '2371c02dcd0b562d3dd7cfb13123f7d426cf4810'], dtype=object)
Coordinates:
  * presentation     (presentation) MultiIndex
  - image_id         (presentation) object 'a533e519b553cdf360ae134f7c9f161134ddaf00' ... 'c33a74c58c05433d6ce418cdfc5a2b2edd5b72dc'
  - repetition       (presentation) int64 0 0 0 0 0 0 0 0 0 ... 0 0 0 1 1 1 1 1
  - stimulus         (presentation) int64 29 67 74 102 160 ... 29 67 74 102 160
  - id               (presentation) int64 30 68 75 103 159 ... 30 68 75 103 159
  - image_file_name  (presentation) object 'face0001_rx+00.000_ry+00.000_rz+00.000_tx+00.000_ty+00.000_s+00.800_840b0badda8be10e1e3d5eff5cedce384f8021bc_256x256.png' ... '_033_r

In [22]:
np.unique(sub["image_id"])

array(['11bfd22097d9c511621ef17b2c13067dc1cd7352',
       '2371c02dcd0b562d3dd7cfb13123f7d426cf4810',
       '2970df86fb9706eb1ef066a7120049eb7bb8656e',
       '2ea3bb4fb4212f49f1382a938351d3c2e8e0a652',
       '36db24ff49d1e53a12af349c465fc32592168b4b',
       '398ece9ff10d90e31c39e0b7625454d81fc19f8d',
       '3a2e8aeaae50f81d1d4fc716969bd2c8e169b9d9',
       '48c621bed18d56770d77b061e01ca33b4548f539',
       '4e05f442f98dceb778e7de1f2d0f700241461756',
       '5546dc0575a1e6477db5f4accd1d17184deb405b',
       '79d8e812eae9ecf647eb1eff72d613dff34b1062',
       '9d89aedf86af6292d4d6fe3774a51c92fb715c4e',
       'a533e519b553cdf360ae134f7c9f161134ddaf00',
       'a7792c8a467907240ca8cd98fa51cf768311e398',
       'ac1db6c2528dd94f07c1ae56b404d73995b5329f',
       'b64a713676ad771e355fe0cad98121f1cb329d92',
       'b713c093a9135539f1fdd0b92c44f59688267561',
       'bffb5a5531aabefe3a9f0eee48963e1dbfc2f5f2',
       'c33a74c58c05433d6ce418cdfc5a2b2edd5b72dc',
       'c4fac169f2c9ce65d464743

In [23]:
len(np.unique(sub["image_id"]))

25

In [27]:
[x for x in sub.coords]

['neuroid', 'presentation', 'time_bin']

In [30]:
[x for x in sub.indexes.keys()]

['neuroid', 'presentation', 'time_bin']

In [32]:
result = xr.DataArray(sub).reset_index("presentation")
result

<xarray.DataArray 'dicarlo.Majaj2015' (neuroid: 296, presentation: 700, time_bin: 1)>
array([[[ 1.928658],
        [ 0.060929],
        ...,
        [-0.623783],
        [ 0.529768]],

       [[ 0.292777],
        [ 1.990058],
        ...,
        [ 0.967823],
        [-0.386514]],

       ...,

       [[ 1.420371],
        [-0.07489 ],
        ...,
        [-1.35632 ],
        [-0.085704]],

       [[ 0.291163],
        [-0.518903],
        ...,
        [ 2.94649 ],
        [-1.835507]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' ... 'Chabo_L_P_7_6'
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' ... 'P' 'P' 'P' 'P'
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 ... 8 7 8 6 7 5 7 7 6 6
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' ... 'L' 'L' 'L' 'L'
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' ... 'V4' 'V4' 'V4'
  - animal           (neuroid) object 'Chab

In [33]:
[x for x in result.coords]

['neuroid',
 'time_bin',
 'image_id',
 'repetition',
 'stimulus',
 'id',
 'image_file_name',
 'object_name',
 'category_name',
 'background_id',
 'variation',
 'ty',
 'tz',
 'rxy',
 'rxz',
 'ryz',
 'rxy_semantic',
 'rxz_semantic',
 'ryz_semantic',
 'size',
 's']

In [36]:
preserve = ['neuroid', 'time_bin','image_id', 'repetition']

In [38]:
remove = [x for x in result.coords if x not in preserve]
remove

['stimulus',
 'id',
 'image_file_name',
 'object_name',
 'category_name',
 'background_id',
 'variation',
 'ty',
 'tz',
 'rxy',
 'rxz',
 'ryz',
 'rxy_semantic',
 'rxz_semantic',
 'ryz_semantic',
 'size',
 's']

In [39]:
result = result.drop(remove)
result

<xarray.DataArray 'dicarlo.Majaj2015' (neuroid: 296, presentation: 700, time_bin: 1)>
array([[[ 1.928658],
        [ 0.060929],
        ...,
        [-0.623783],
        [ 0.529768]],

       [[ 0.292777],
        [ 1.990058],
        ...,
        [ 0.967823],
        [-0.386514]],

       ...,

       [[ 1.420371],
        [-0.07489 ],
        ...,
        [-1.35632 ],
        [-0.085704]],

       [[ 0.291163],
        [-0.518903],
        ...,
        [ 2.94649 ],
        [-1.835507]]], dtype=float32)
Coordinates:
  * neuroid         (neuroid) MultiIndex
  - neuroid_id      (neuroid) object 'Chabo_L_M_5_9' ... 'Chabo_L_P_7_6'
  - arr             (neuroid) object 'M' 'M' 'M' 'M' 'M' ... 'P' 'P' 'P' 'P' 'P'
  - col             (neuroid) int64 9 9 8 9 8 8 7 7 5 6 ... 8 7 8 6 7 5 7 7 6 6
  - hemisphere      (neuroid) object 'L' 'L' 'L' 'L' 'L' ... 'L' 'L' 'L' 'L' 'L'
  - subregion       (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' ... 'V4' 'V4' 'V4'
  - animal          (neuroid) object 'Cha

In [42]:
target_netcdf = Path(target_dir).parent / "test_data.nc"

In [44]:
del result.attrs["stimulus_set"]

In [47]:
result = result.reset_index(["neuroid", "time_bin"])
result

KeyError: 'neuroid'

In [48]:
result.to_netcdf(target_netcdf)