In [1]:
from dldata.stimulus_sets.rust_datasets import Rust305ImageSet

In [2]:
rust_dldata = Rust305ImageSet()
rust_dldata

In [3]:
rust_dldata.get_images

<bound method Rust305ImageSet.get_images of <dldata.stimulus_sets.rust_datasets.Rust305ImageSet object at 0x7fdfc0041750>>

In [4]:
rust_dldata.neuronal_features_Rust

array([[ 3.4,  1.4,  2.6, ...,  0.6,  3.4,  1.2],
       [ 2.4,  0.8,  0.4, ...,  0.2,  4.4,  0.6],
       [ 3. ,  4.6,  2. , ...,  0.2,  3.6,  0. ],
       ..., 
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ]])

In [5]:
rust_dldata.neuronal_features_Rust.shape

(305, 285)

In [7]:
rust_dldata.neuronal_features_reps_Rust

array([[[ 5.,  0.,  3., ...,  2.,  3.,  0.],
        [ 4.,  4.,  0., ...,  1.,  7.,  0.],
        [ 3.,  2.,  1., ...,  1.,  2.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  1.,  1., ...,  1.,  3.,  4.],
        [ 3.,  0.,  0., ...,  0.,  4.,  1.],
        [ 0.,  9.,  4., ...,  0.,  4.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 3.,  3.,  0., ...,  0.,  4.,  0.],
        [ 1.,  0.,  0., ...,  0.,  4.,  1.],
        [ 4.,  0.,  0., ...,  0.,  6.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 7.,  3.,  2., ...,  0.,  3.,  2.],
        [ 2.,  0.,  2., ...,  0.,  5.,  1.],
        [ 5.,  6.,  1., ...,  0.,  2.,  0.],
       

In [6]:
rust_dldata.neuronal_features_reps_Rust.shape

(5, 305, 285)

In [8]:
rust_dldata.meta

tabarray([(0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_1.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_2.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_3.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_4.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_5.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_6.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_7.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_8.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_9.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_10.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_11.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_12.png'),
          (0, '/braintree/home/jjpr/.skdata/Rust305/imgs/Nat300_13.png'),
          (0, '/braintree/home/jjpr/.skdata/Rus

In [10]:
rust_dldata.meta.shape

(305,)

In [9]:
rust_dldata.categories

ValueError: no field of name category

In [11]:
len(rust_dldata.V4_NEURONS_Rust) + len(rust_dldata.IT_NEURONS_Rust)

285

In [12]:
rust_dldata.neuronal_features_HongMajaj

AttributeError: 'module' object has no attribute 'openFile'

In [13]:
rust_dldata.neuronal_features_reps_Rust

array([[[ 5.,  0.,  3., ...,  2.,  3.,  0.],
        [ 4.,  4.,  0., ...,  1.,  7.,  0.],
        [ 3.,  2.,  1., ...,  1.,  2.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  1.,  1., ...,  1.,  3.,  4.],
        [ 3.,  0.,  0., ...,  0.,  4.,  1.],
        [ 0.,  9.,  4., ...,  0.,  4.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 3.,  3.,  0., ...,  0.,  4.,  0.],
        [ 1.,  0.,  0., ...,  0.,  4.,  1.],
        [ 4.,  0.,  0., ...,  0.,  6.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 7.,  3.,  2., ...,  0.,  3.,  2.],
        [ 2.,  0.,  2., ...,  0.,  5.,  1.],
        [ 5.,  6.,  1., ...,  0.,  2.,  0.],
       

In [14]:
rust_dldata.neuronal_features_reps_Rust.shape

(5, 305, 285)

In [15]:
type(rust_dldata.neuronal_features_reps_Rust)

numpy.ndarray